# Generated by Django 5.0.6 on 2024-06-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_checkout_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
