# Generated by Django 5.0.6 on 2024-06-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_menu_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
