# Generated by Django 5.0.6 on 2025-01-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_restaurantdetails_alter_menu_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetails',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantdetails',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
