# Generated by Django 5.0.6 on 2025-01-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_before_tax',
            field=models.FloatField(default=0),
        ),
    ]
