# Generated by Django 5.0.6 on 2025-01-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
