# Generated by Django 6.0.1 on 2026-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0028_order_delivery_boy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodcategory",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="category_images"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="foodimage"),
        ),
    ]
