# Generated by Django 6.0.1 on 2026-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0029_alter_foodcategory_image_alter_menu_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
