# Generated by Django 6.0.1 on 2026-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Products", "0030_alter_foodcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodcategory",
            name="image",
            field=models.FileField(
                blank=True,
                default="category_images/food.png",
                null=True,
                upload_to="category_images",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="image",
            field=models.FileField(
                blank=True,
                default="foodimage/food.png",
                null=True,
                upload_to="foodimage",
            ),
        ),
    ]
