# Generated by Django 5.0.6 on 2026-06-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_alter_foodcategory_image_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetails',
            name='default_printer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdetails',
            name='printing_method',
            field=models.CharField(choices=[('CLIENT', 'Client-Side (Browser Print via iframe)'), ('SERVER', 'Server-Side Direct Print (Windows win32print)')], default='CLIENT', max_length=10),
        ),
    ]
