# Generated by Django 5.0.6 on 2026-06-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_restaurantdetails_default_printer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetails',
            name='paper_width',
            field=models.CharField(choices=[('58mm', '2 Inch (58mm)'), ('80mm', '3 Inch (80mm)'), ('100mm', '4 Inch (100mm)')], default='80mm', max_length=10),
        ),
    ]
