# Generated by Django 5.0.6 on 2026-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_restaurantdetails_paper_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetails',
            name='print_copies',
            field=models.IntegerField(choices=[(1, '1 Copy'), (2, '2 Copies')], default=1),
        ),
    ]
